workshop2:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host_name
      user: postgresadmin
      password: your_password
      port: port_number
      dbname: your_db_name
      schema: your_schema_name
    staging:
      type: postgres
      host: host_name
      user: your_user_name
      password: your_password
      port: port_number
      dbname: your_db_name
      schema: your_schema_name
