{{ config(materialized='view') }}

SELECT
    uid AS episode_uid,
    createdatetime AS created_at,
    updatedatetime AS updated_at,
    --structuraltype AS structural_type,
    --referenttype AS referent_type,
    episodeclass AS episode_class,
    episodenumber AS episode_number,
    title120 AS title_120,
    titleclass AS title_class,
    titlelanguage AS title_language,
    --emm_episode_uid,
    --emm_parent_uid,
    series_uid,
    season_uid,
    countryoforigin AS country_of_origin,
    primarygenre AS primary_genre,
    secondarygenre AS secondary_genre,
    distribution_number,
    approximate_length,
    eidr_id,
    entity_type,
    primary_mode,
    primary_language,
    secondary_language,
    synopsisshort AS synopsis_short,
    synopsislong AS synopsis_long,
    published_status,
    -- deletedatetime::timestamp AS deleted_at,
    -- is_deleted::boolean,
    title19,
    title,
    titlelong AS title_long,
    keyword_mood,
    keyword_time_period,
    keyword_theme,
    keyword_characters,
    keyword_setting,
    keyword_subject,
    keyword_general,
    tv_rating,
    contentid_list,
    release_date
FROM {{ ref('int_cleansed_episode') }}